# Generated by Django 5.1.1 on 2024-10-05 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_remove_evento_ubicacion_alter_evento_fecha_creacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ubicacion',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='evento',
            name='lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='max_participantes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='evento',
            name='participantes',
            field=models.ManyToManyField(related_name='eventos_participantes', to=settings.AUTH_USER_MODEL),
        ),
    ]
