# Generated by Django 5.1.1 on 2024-10-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_evento_ubicacion_alter_evento_lider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='participantes',
        ),
        migrations.AlterField(
            model_name='evento',
            name='ubicacion',
            field=models.CharField(max_length=255),
        ),
    ]
