# Generated by Django 5.1.1 on 2024-10-26 00:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_evento_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Formato de hora inválido. Usa hh:mm AM/PM.', regex='^(0[1-9]|1[0-2]):[0-5][0-9] (AM|PM)$')]),
        ),
        migrations.AlterField(
            model_name='evento',
            name='ubicacion',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Formato de coordenada inválido. Usa 'latitud, longitud'.", regex='^-?\\d{1,2}\\.\\d+,\\s*-?\\d{1,3}\\.\\d+$')]),
        ),
    ]
